diff --git a/Makefile b/Makefile
index f36f6b022..57b3a9519 100644
--- a/Makefile
+++ b/Makefile
@@ -48,8 +48,15 @@ initramfs := $(wrkdir)/initramfs.cpio.gz
 
 opensbi_srcdir := $(srcdir)/opensbi
 opensbi_wrkdir := $(wrkdir)/opensbi
-opensbi_payload := $(opensbi_wrkdir)/platform/nuclei/ux600/firmware/fw_payload.elf
-opensbi_jumpbin := $(opensbi_wrkdir)/platform/nuclei/ux600/firmware/fw_jump.bin
+# Pure DT-driven OpenSBI: PLATFORM=generic with no override module,
+# no per-board platform/ directory. Everything specific to the SoC
+# lives in the DTS (conf/nuclei_ux600fd.dts) and the freeloader's
+# SoC-bringup sequence (DDR + cache + UART setup register).
+opensbi_platform := generic
+opensbi_fw_text  := 0x41000000
+opensbi_fw_fdt   := 0x48000000
+opensbi_payload := $(opensbi_wrkdir)/platform/$(opensbi_platform)/firmware/fw_payload.elf
+opensbi_jumpbin := $(opensbi_wrkdir)/platform/$(opensbi_platform)/firmware/fw_jump.bin
 
 freeloader_srcdir := $(srcdir)/freeloader
 freeloader_wrkdir := $(srcdir)/freeloader
@@ -208,14 +215,17 @@ $(opensbi_jumpbin):
 	rm -rf $(opensbi_wrkdir)
 	$(MAKE) -C $(opensbi_srcdir) O=$(opensbi_wrkdir) CROSS_COMPILE=$(CROSS_COMPILE) \
 		PLATFORM_RISCV_ABI=$(ABI) PLATFORM_RISCV_ISA=$(ISA) \
-		PLATFORM=nuclei/ux600
+		PLATFORM=$(opensbi_platform) \
+		FW_TEXT_START=$(opensbi_fw_text) FW_JUMP_FDT_ADDR=$(opensbi_fw_fdt)
 
 $(opensbi_payload): $(opensbi_srcdir) $(vmlinux_bin) $(platform_sim_dtb)
 	rm -rf $(opensbi_wrkdir)
 	mkdir -p $(opensbi_wrkdir)
 	$(MAKE) -C $(opensbi_srcdir) O=$(opensbi_wrkdir) CROSS_COMPILE=$(CROSS_COMPILE) \
 		PLATFORM_RISCV_ABI=$(ABI) PLATFORM_RISCV_ISA=$(ISA) \
-		PLATFORM=nuclei/ux600 FW_PAYLOAD_PATH=$(vmlinux_bin) FW_PAYLOAD_FDT_PATH=$(platform_sim_dtb)
+		PLATFORM=$(opensbi_platform) \
+		FW_TEXT_START=$(opensbi_fw_text) FW_PAYLOAD_FDT_ADDR=$(opensbi_fw_fdt) \
+		FW_PAYLOAD_PATH=$(vmlinux_bin) FW_PAYLOAD_FDT_PATH=$(platform_sim_dtb)
 
 $(buildroot_initramfs_sysroot): $(buildroot_initramfs_sysroot_stamp)
 
